version: '3.8'

services:
  nader-ai-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./engine/logs:/app/engine/logs
    networks:
      - nader-ai-network

  telegram:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    command: ["python", "-m", "engine.packages.telegram"]
    networks:
      - nader-ai-network


networks:
  nader-ai-network:
    driver: bridge
